### ISSUE TITLE
Clarify the license terms

### ISSUE THREAD

**Issue by jserv** [joshlvmh/iqtree_arm_neon#3]
This project states the license terms as following:
> Copyright (C) 2020 Joshua Measure-Hughes
> Written for the Advanced Computing Research Centre, University of Bristol.
> Licensed under the MIT License, (the “License”); you may not use this file except in compliance with the License.

I assume that this project was derived from [IQ-TREE](https://github.com/Cibiv/IQ-TREE), which is licensed under GNU GPL. It makes me a bit confused that the derived work from a GPL'd work should remain the same license terms according to GNU GPL. Can you clarify this?

**Comment by joshlvmh** [comment]
Thank you for pointing this out, I realised I did not put in a note saying the license only applied to unique additions/files rather than modifications. I will add that now.
________________________________

**Comment by jserv** [comment]
> Thank you for pointing this out, I realised I did not put in a note saying the license only applied to unique additions/files rather than modifications. I will add that now.

As the maintainer of [sse2neon](https://github.com/DLTcollab/sse2neon), I would like to mention your effort on Arm NEON port of IQ-TREE as the adoption case. However, I was hesitant because of uncertain license terms here. Good to hear the further clarification.

**Comment by joshlvmh** [comment]
Thank you, please do let me know if there is anything else. I have been meaning to contact the sse2neon team to make them aware of my additions, so you beat me to it!

**Comment by jserv** [comment]
Got it. I have read the updated `README.md` and understood.
